export const GET_SEARCH_DATA_START = "GET_SEARCH_DATA_START";
export const GET_SEARCH_DATA_SUCCESS = "GET_SEARCH_DATA_SUCCESS";
export const GET_SEARCH_DATA_ERROR = "GET_SEARCH_DATA_ERROR";
export const GET_SEARCH_DATA_CLEAR = "GET_SEARCH_DATA_CLEAR"